### ISSUE TITLE
slack/notify in a Workflow: fail_only: "true" reports to Slack also for green jobs

### ISSUE THREAD

**Issue by olleolleolle** [CircleCI-Public/slack-orb#1]
I installed the Orb today, and tried it in a PR. The installation instructions are good.

I use `workflows`, like this (fragment):

```yaml
orbs:
  slack: circleci/slack@0.1.0

version: 2.1
jobs:
  # more jobs here...
  alert_me:
    docker:
      - image: circleci/node
    # https://github.com/CircleCI-Public/slack-orb
    steps:
      - slack/status:
        fail_only: "true"

workflows:
  version: 2
  test:
    jobs:
      - checkout_code
      - frontend:
          context: org-global
          requires:
            - checkout_code
      - backend:
          context: org-global
          requires:
            - checkout_code
      - alert_me:
          context: org-global
          requires:
            - backend
            - frontend
```

**Expected**: What I expected was that the Slack notification would _not_ fire, as the Status was green.

**Actual**: But, the Slack channel received notifications such as "A job has succeeded!".

Does this note

> Must be last step in job

mean I'm trying to use it wrong?
