### ISSUE TITLE
Unable to send from tag build

### ISSUE THREAD

**Issue by jodastephen** [CircleCI-Public/slack-orb#124]
### Orb version

v3.4.0

### What happened

Error "Current branch is not included in only_for_branches filter; no status alert will be sent" is output. This occurs with config:

```
      - slack/status:
          channel: XXXXXXX
          failure_message: 'failed'
          fail_only: true
          only_for_branches: master
```

This happens because on a tag build, `$CIRCLE_BRANCH` is not set, so the ORB fails to correctly  match the branch name.

### Expected behavior

The slack message should be sent.
