### ISSUE TITLE
[Question] show the branch name in the slack message

### ISSUE THREAD

**Issue by GabrielPeral** [CircleCI-Public/slack-orb#137]
Hi,
it would be possible to add a field in the message that says in which **branch** the error and/or success has been done? in the `status` command

**Comment by emma-sax4** [comment]
One thing I've been experimenting with is this:
```yml
- slack/status:
    failure_message: "Build #${CIRCLE_BUILD_NUM} of ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}@${CIRCLE_BRANCH} by ${CIRCLE_USERNAME} failed."
fail_only: true
    include_job_number_field: false
    include_project_field: false
```
It's not a link, but the attachment button will be a link to the build.
