### ISSUE TITLE
using with windows executor

### ISSUE THREAD

**Issue by nicks** [CircleCI-Public/slack-orb#145]
### Orb version
3.4.0

### What happened

On all my builds, I have

```
      - slack/notify-on-failure:
          only_for_branches: master
```

I'd like to also add this for my Windows executor.

```

  build-windows:
    executor:
      name: win/default
      size: "medium"
    steps:
      - checkout
      - run: go test ./...
      - slack/notify-on-failure:
          only_for_branches: master
```

This fails with the following error:

```
Provide error if non-bash shell
#!powershell.exe -ExecutionPolicy Bypass
if [ ! -x /bin/bash ]; then
  echo Bash not installed.
  exit 1
fi
```

I understand why the error is happening. But I'm not sure if there's an alternative way to accomplish this. Any ideas?
