### ISSUE TITLE
Getting "Cannot find a definition for command named status" error

### ISSUE THREAD

**Issue by bizmonogatari** [CircleCI-Public/slack-orb#148]
### Orb version
3.4.2

### What happened

```
#!/bin/sh -eo pipefail
# Error calling workflow: 'build-deploy'
# Error calling job: 'build-deploy-stg'
# Error calling command: 'notify'
# Cannot find a definition for command named status
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false

Exited with code exit status 1
CircleCI received exit code 1
```

I get the above error when trying to run CI with the below config.
I have checked locally that the config is valid using ```circleci config validate```

```
version: 2.1
orbs:
  slack: circleci/slack@3.4.2
executors:
  build_container:
    docker:
      - image: circleci/python:3.7.1-node
commands:
  build:
    parameters:
      target:
        type: string
    steps:
      - run: mkdir -p /tmp/workspace
      - checkout
      - run:
          name: install dependencies
          command: yarn
      - run:
          name: test
          command: yarn test
      - run:
          name: setup contentful
          command: |
            echo "export CONTENTFUL_SPACE_ID=$<< parameters.target >>_CONTENTFUL_SPACE_ID" >> $BASH_ENV
            echo "export CONTENTFUL_ACCESS_TOKEN=$<< parameters.target >>_CONTENTFUL_ACCESS_TOKEN" >> $BASH_ENV
      - run:
          name: build
          command: yarn build $CONTENTFUL_SLUG
      - run: cp -r packages /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - packages
  deploy:
    parameters:
      target:
        type: string
      bucket:
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: setup awscli
          command: |
            sudo pip install awscli
            echo "export AWS_ACCESS_KEY_ID=$<< parameters.target >>_AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$<< parameters.target >>_AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
      - run:
          name: put resources to s3
          command: |
            cd /tmp/workspace
            aws s3 sync packages/lp/$CONTENTFUL_SLUG/public s3://<< parameters.bucket >>/lp/$CONTENTFUL_SLUG --delete --cache-control "public, max-age=0, must-revalidate"
            aws s3 sync packages/lp/$CONTENTFUL_SLUG/public/cms_assets s3://<< parameters.bucket >>/cms_assets --exclude "*page-data/*" --cache-control "public, max-age=31536000, immutable"
            aws s3 sync packages/lp/$CONTENTFUL_SLUG/public/cms_assets/lp/$CONTENTFUL_SLUG/page-data s3://<< parameters.bucket >>/cms_assets/lp/$CONTENTFUL_SLUG/page-data --cache-control "public, max-age=0, must-revalidate"
            aws s3 rm s3://<< parameters.bucket >>/lp/$CONTENTFUL_SLUG/cms_assets --recursive
  build-stg:
    steps:
      - build:
          target: STAGING
  deploy-stg:
    steps:
      - deploy:
          target: STAGING
          bucket: myBucket.org
  notify:
    parameters:
      webhook:
        type: string
    steps:
      - slack/status:
          failure_message: ':cms: A $CIRCLE_JOB job has failed! :cms:'
          only_for_branches: master
          webhook: << parameters.webhook >>
jobs:
  build-deploy-stg:
    executor: build_container
    steps:
      - build-stg
      - deploy-stg
      - notify:
          webhook: http/mywebhook
  delete-prod:
    executor: build_container
    steps:
      - delete-prod
  delete-stg:
    executor: build_container
    steps:
      - delete-stg
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy-stg
    triggers:
      - schedule:
          cron: '0 0 * * 3'
          filters:
            branches:
              only:
                - master
                - circleci-test
```

### Expected behavior

No error is raised.

**Comment by albertoal** [comment]
Getting the same error. The orb doesn't work when using it within API-triggered jobs as described in here: https://circleci.com/docs/2.0/api-job-trigger/#section=jobs

Interestingly, I'm able to use non-official orbs or orbs authored by myself when triggering jobs via the API, so I assume there is some namespacing issue that only occurs when using official orbs as the error doesn't include the `slack/*` prefix, only the actual orb command so it looks like it's being stripped in the final config. 

Going to fork this Orb and try using it as a private orb instead. Will report results.

**Comment by albertoal** [comment]
Unfortunately authoring the orb results in the same issue. It seems that the `slack/*` prefix only gets stripped when customizing orb commands:

So basically this configuration fails:
```yaml
    steps:
      - slack/status:
          failure_message: ':cms: A $CIRCLE_JOB job has failed! :cms:'
      - run:
          name: foo 
          command: |
            echo bar
```

But if you use this instead, then it doesn't:
```yaml
    steps:
      - slack/status
      - run:
          name: foo 
          command: |
            echo bar
```

The problem with the second approach is that you cannot customize the notifications further. I opened a support ticket as this seems like a bug with orbs more than this specific one. I was able to confirm this behaviour on both authored and official CircleCI orbs
