### ISSUE TITLE
Customisation of the slack message with buttons and giphy

### ISSUE THREAD

**Issue by jkotchoff** [CircleCI-Public/slack-orb#159]
Having just come across to try circleci as an alternative to bitrise, it's a bit disappointing that this slack integration isn't more flexible.

For example, in bitrise, it's pretty easy to check the build status (to see if it has changed from red to green or vice versa from the prior build) and then only show an appropriate slack message with buttons linking to the build and the commit, the actual commit title and body, the name of the co-authors of the commit, and a relevant giphy animation:
![Screen Shot 2020-08-08 at 5 45 38 pm](https://user-images.githubusercontent.com/58198/89705237-01b6b500-d99f-11ea-9ff3-cb56fcce5b8e.png)

For example, here is how that would work in the bitrise slack integration:
```
- build-status-change@0.1:
    title: Determine if build status changed
    inputs:
      - access_token: '$BUILD_STATUS_ACCESS_TOKEN'
      - verbose: 'yes'
- script@1.1.6:
    title: Set Giphy keywords
    inputs:
      - content: |-
          #!/bin/bash
          set -e
          set -x

          if [ $BITRISE_BUILD_STATUS -eq 1 ]
            then envman add --key GIPHY_KEYWORDS --value "embarrassing,fail,disappointed,try again,meh"
            else envman add --key GIPHY_KEYWORDS --value "ferda,success,congrats,victory,awesome,shipit,hell yeah,applaud,lgtm,yeah,high five,legendary"
          fi
    is_always_run: true
- giphy@0.2.0:
    title: Set Giphy image
    inputs:
      - gif_words: '$GIPHY_KEYWORDS'
- slack@3.1.3:
    title: Notify Slack if build status changed
    run_if: '{{enveq "BUILD_STATUS_CHANGED" "true"}}'
    inputs:
      - webhook_url: xxx
      - channel: '#development'
      - channel_on_error: '#development'
      - author_name: 'Build #$BITRISE_BUILD_NUMBER triggered by $GIT_CLONE_COMMIT_AUTHOR_NAME'
      - message: ':white_check_mark: Woot! Build was succesful'
      - message_on_error: "\U0001F631 Bugger, Something went wrong"
      - fields: []
      - buttons: |-
          View on Bitrise|${BITRISE_BUILD_URL}
          View on GitHub|$GITHUB_URL
      - image_url: '$GIF_URL'
```

It would seem that circleci should be able to make this slack orb have equivalent functionality?

**Comment by KyleTryon** [comment]
Hello @jkotchoff,

We are currently working on a major overhaul to the slack orb that I believe should resolve this, we would love your opinion.
https://github.com/CircleCI-Public/slack-orb/tree/Major-block-kit-redesign

This new iteration makes use of pre-made templates and the ability to include your own via Slack's block-kit-builder

**Comment by jkotchoff** [comment]
Hey Kyle, thanks for following up. The new overhaul looks great from the perspective of being able to customise the slack message content so kudos for that. 

However, without being able to configure it specifically for build status changes, it seems like a big downgrade from bitrise. I note that James from Expo already [customised your slack implementation](https://github.com/CircleCI-Public/slack-orb/issues/54#issuecomment-531401832) in that way and so it seems like it should also be possible for circleci.

In terms of opinion, not being able to also configure relevant giphy's for the slack message per the above example also seems like an area where bitrise is much more powerful. Basically, everything in the above example (eg. the git commit title/body, the git commit user(s), a link to github, different messages for successful versus failed builds) would be features that I would consider desirable if you are looking to really improve the orb with the overhaul.

**Comment by KyleTryon** [comment]
Giphy is something that seems easy enough to support. Unfortunately, I am warry of including a "fixed" status for the Slack orb as currently there is no such thing as a "fixed" pipeline on CircleCI. The designs of pipelines on CircleCI 2.0 makes it a little difficult in all situations to rely on the status of any single job to represent a "fixed" status. There is a current feature request out now for a "fixed" status for workflows.
https://ideas.circleci.com/ideas/CCI-I-629

I'll also pass up the feedback 👍  thank you. Please feel free to send in a vote and also get any updates related to the request.

We are also making progress toward native webhooks which will offer additional benefits we'll be able to make use of, such as hopefully a true slack bot in the future. As the webhook endpoint list grows we'll be able to extend in that way as well.

As for including the author name and such in the orb solution, in the new Slack Orb I believe this shouldn't be an issue. You should be able to include any custom information via environment variables in very much the same way you are showing above if I understand correctly.

I plan to add more templates, each of which may expect a different set of environment variables, but here is the example for a custom message template:

```yaml
- slack/notify:
    event: always
    custom: |
      {
        "blocks": [
          {
            "type": "section",
            "fields": [
              {
                "type": "plain_text",
                "text": "$MYCUSTOMVAR",
                "emoji": true
              }
            ]
          }
        ]
      }
```

You should be able to create a custom template using the Slack Block-Kit-Builder, and insert any custom information you want. CircleCI already provides [environment variables](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) containing information about the commit, author, pr, etc. The status of the last time the job was run on that branch is not something included by default, but as you linked to, could be generated (for the time being).

I do need to do a little more digging on that Giphy integration. It seems from the code you posted they are using incoming webhooks, as are we, but those do not allow for file upload. If a Giphy URL will display natively, it would be trivial to add.
