### ISSUE TITLE
slack/notify not working properly

### ISSUE THREAD

**Issue by simplekjl** [CircleCI-Public/slack-orb#168]
### Orb version

 slack@3.4.2

### What happened

  Whenever I refer to the variable `- slack/notify` I get the message that the variable doesn't exist

`Error calling workflow: 'ci' Cannot find a definition for job named slack/status`

Here some of the configuration

````
workflows:
  ci:
    jobs:
      - dependencies:
          filters:
            branches:
              ignore:
                - master

      - check:
          requires:
            - dependencies

      - slack/approval-notification:
          message: ${CIRCLE_USERNAME} has created a new job that has to be reviewed
            ${CIRCLE_BRANCH}
          webhook: ${SLACK_WEBHOOK}

      - slack/status:
          fail_only: false
          only_for_branches: "master"
          weebhook: ${SLACK_WEBHOOK}


      - jacoco:
          type: approval
          requires:
            - check

      - testlab_app:
          requires:
            - jacoco
      - testlab_feature:
          requires:
            - jacoco
      - testlab_robo:
          requires:
            - jacoco

      - distribution_qa:
          type: approval
          requires:
            - testlab_app
            - testlab_feature
            - testlab_robo
````

### Expected behavior

well... the configuration looks pretty straightforward but seems that is not working? 
According to the configuration page I can place status at any part of the workflow.

**Comment by KyleTryon** [comment]
Hello @simplekjl,

There are two issues here what would prevent this from working properly.

```
      - slack/status:
          fail_only: false
          only_for_branches: "master"
          weebhook: ${SLACK_WEBHOOK}
```

"status" is a _command_, rather than a _job_, but is being called from your workflow as if it were a job.
The status command must be used as the last command within a job.

View this usage example from the orb registry:

https://circleci.com/orbs/registry/orb/circleci/slack#usage-status
```
jobs:
  build:
    docker:
      - image: <docker image>
    steps:
      - run: exit 0
      - slack/status:
          fail_only: true
          mentions: 'USERID1,USERID2'
          only_for_branches: only_for_branches
          webhook: webhook
```

Also ensure to correct `weebhook` > `webhook`.

Let us know if you run into any further trouble and we will re-open the issue! Thank you.
