### ISSUE TITLE
Send slack notification only on failed builds on master branch

### ISSUE THREAD

**Issue by gsaslis** [CircleCI-Public/slack-orb#17]
Hi there, 

our team's workflow is such that we don't want slack notifications for _all_ the builds on pull requests. 

We do want to get notified on slack if a build fails on `master` branch only (or maybe even set of branches). 

As far as I have seen, this use case is not currently covered by this orb. So: 
* Am I wrong?
* If not, would you agree this is a valid use case ?

**Comment by zzak** [comment]
Hello @gsaslis,

You can specify to use `slack/status` command to send notifications only when builds fail -- but I don't think you can specify branches at the moment.

That's a great feature request!

To simplify my config, I add this command inline to my config so it's easy to call the slack command for only failing jobs:

```yaml
commands:
  # Wrap the slack/status command to only notify on failures
  slack:
    steps:
      - slack-orb/status:
          fail_only: "true"
```
