### ISSUE TITLE
Backticks for inline code formatting are incorrectly parsed

### ISSUE THREAD

**Issue by metalrex100** [CircleCI-Public/slack-orb#182]
## Orb version: 
4.0.0

## What happened: 
Backticks for inline code formatting hide the content inside them. If I try to escape them with `\`, build fails with message: `parse error: Invalid escape at line 1, column 291`

## Expected behavior:

Backtics should add inline-code formatting to string as it is done in slack app.

**Comment by KyleTryon** [comment]
@metalrex100 could you share the exact command you have tried with all included parameters and values? Thank you. We will try to resolve this asap

**Comment by metalrex100** [comment]
@KyleTryon sure.

Special for testing this bug I've created notification with slack Block kit builder.
The full notification code in CicleCI config:

```
- slack/notify:
    custom: |
      {"attachments":[{"color":"#ed5c5c","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"text in backtics: `some text`, variable in backtics `$CIRCLE_JOB`"}},{"type":"divider"}]}]}
    event: pass
```

In slack Block kit builder preview message formatting looks correct: 
https://app.slack.com/block-kit-builder/T3HQ2JXGX#%7B%22attachments%22:%5B%7B%22color%22:%22#ed5c5c%22,%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22text%20in%20backtics:%20%60some%20text%60,%20variable%20in%20backtics%20%60$CIRCLE_JOB%60%22%7D%7D,%7B%22type%22:%22divider%22%7D%5D%7D%5D%7D

But when CircleCI sends notification to slack, I receive this (as you can see content in backtics just disappeared):

![image](https://user-images.githubusercontent.com/22449118/95971749-44bb5b80-0e1a-11eb-98af-a95a7bd87977.png)
