### ISSUE TITLE
CI says success, but no message appears in slack?

### ISSUE THREAD

**Issue by frehner** [CircleCI-Public/slack-orb#184]
## Orb version:

`circleci/slack@4.0.0`

## What happened:

Currently just trying to set up the notification, so I'm intentionally failing a job so that the orb will notify a slack channel. My job looks like this:

```yml
jobs:
  install:
    executor:
      <<: *defaultExecutor
    steps:
      - run:
          name: exit 1
          command: exit 1
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: *******FJT # commented out for this issue. I also setup the SLACK_DEFAULT_CHANNEL env var too

workflows:
  test_and_deploy:
    jobs:
      - install:
          context:
            - frontend-build-deploy-s3
```

Circle fails (successfully) on the first step, then runs the slack steps. It appears to run successfully - here's a screenshot

<img width="1430" alt="Screen Shot 2020-10-09 at 10 22 30 AM" src="https://user-images.githubusercontent.com/3054066/95607696-5915e780-0a19-11eb-9e33-e80a0b87623a.png">

Here's a link to the workflow:

https://app.circleci.com/pipelines/github/patterninc/shelf-ui/2130/workflows/3847fb06-8648-479a-8ed8-80e6803f7a79/jobs/2535

From what I can tell, it all appears to "work"... yet I'm not getting any slack notifications. I've probably misconfigured it somehow, but there aren't any error messages or debug info that I can see that would help me figure out what is going on. 

## Expected behavior:

Notifies slack

## Additional Information:

I think I added as much as I could above, but let me know if you need more.

Thank you!
