### ISSUE TITLE
Crashes on apostrophe

### ISSUE THREAD

**Issue by adamu** [CircleCI-Public/slack-orb#186]
## Orb version:

4.0.0
## What happened:

Orb crashes when the payload contains an apostrophe
## Expected behavior:
Doesn't crash

## Additional Information:
Config:

```yml
      - slack/notify:
          channel: test-webhook
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "I'm Circle CI"
                  }
                }
              ]
            }
          event: always
```

Orb output:

```
Checking For JQ + CURL: Debian
/bin/bash: eval: line 8: unexpected EOF while looking for matching `''
/bin/bash: eval: line 9: syntax error: unexpected end of file

Exited with code exit status 1

CircleCI received exit code 1
```

If I change the text to `"Im Circle CI"`, it doesn't crash.
