### ISSUE TITLE
Cannot find a definition for command named notify/status

### ISSUE THREAD

**Issue by tmaly1980** [CircleCI-Public/slack-orb#191]
## Orb version:

3.4.2

## What happened:

I cannot get CircleCI to recognize my slack integration. It's saying:

```
Cannot find a definition for command named notify
```

I'm specifically calling the build-ios job from the CircleCI API like so:
```
POST https://circleci.com/api/v1.1/project/bitbucket/USER/REPO
```

Payload is:
```
{
   "build_parameters": { 
       "CIRCLE_JOB": "build-ios",
       "APPNAME": "app1"
   }
}
```

## Expected behavior:

It should understand the slack/notify and slack/status commands. I've followed the documentation here: https://circleci.com/developer/orbs/orb/circleci/slack?version=3.4.2#usage-notify

It specifically says "Notify a slack channel with a custom message at any point in a job with this custom step", so I'm expecting it to work at the beginning of the list rather than just the end. I've even removed the slack/notify and left just slack/status at the end of my job list, and that fails too.

## Additional Information:

Here is my config.yml:

```
version: 2.1
orbs:
  slack: circleci/slack@3.4.2
defaults: &defaults
  macos:
    xcode: 11.4.1
  working_directory: ~/project
npm_install: &npm_install
  name: NPM install
  command: npm install
brew_install: &brew_install
  name: Homebrew install
  command: brew install imagemagick
jobs:
  default:
    <<: *defaults
    steps:
      - run:
          name: Default job
          command: echo "Not running default job (on push)"
  build-ios:
    <<: *defaults
    steps:
      - checkout
      - slack/notify:
          message: Starting ios build #${CIRCLE_BUILD_NUM} ${CIRCLE_JOB} on ${CIRCLECI_BRANCH}
          webhook: ${SLACK_WEBHOOK}
      - run:
          name: Bundle install
          command: cd ios; bundle install
      - run:
          <<: *npm_install
      - run:
          <<: *brew_install
      - run:
          name: iOS - build
          command: |
            yarn fastlane-ios build app:$APPNAME
          no_output_timeout: 30m
      - slack/status:
          webhook: ${SLACK_WEBHOOK}
workflows:
  default:
    jobs:
      - default:
          filters:
            branches:
              only:
                - master-NONE
```

**Comment by KyleTryon** [comment]
Hello @tmaly1980,

It looks like you are using version 3.4.2, is that correct? Please try implementing the new Slack orb V4 listed here:https://circleci.com/developer/orbs/orb/circleci/slack

**Comment by tmaly1980** [comment]
@KyleTryon I've tried both versions. 3.4.2 is still officially supported from what I can tell. 4.0.1 doesn't work for me either. I must be doing something wrong. I need to be able to call slack based on a job triggered from the API, maybe it only can be used from a standard workflow?

```
version: 2.1
orbs:
  slack: circleci/slack@4.0.1
defaults: &defaults
  macos:
    xcode: 11.4.1
  working_directory: ~/project
npm_install: &npm_install
  name: NPM install
  command: npm install
brew_install: &brew_install
  name: Homebrew install
  command: brew install imagemagick
jobs:
  default:
    <<: *defaults
    steps:
      - run:
          name: Default job
          command: echo "Not running default job (on push)"=
  build-ios:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Bundle install
          command: cd ios; bundle install
      - run:
          <<: *npm_install
      - run:
          <<: *brew_install
      - run:
          name: iOS - build
          command: |
            yarn fastlane-ios build app:$APPNAME
          no_output_timeout: 30m
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  default:
    jobs:
      - default:
          filters:
            branches:
              only:
                - master-NONE
```
