### ISSUE TITLE
Sending notification success but nothing appears in Slack

### ISSUE THREAD

**Issue by joelngwt** [CircleCI-Public/slack-orb#197]
## What happened:

Not really a bug report (or maybe it is), but I opened a support ticket on CircleCI and they asked me to ask here, so here I am.

I've followed the instructions on https://github.com/CircleCI-Public/slack-orb/wiki/Setup, and I've also seen this issue: https://github.com/CircleCI-Public/slack-orb/issues/184

- I have created a new Slack app
- I have invited the app to my channel
- I have added the `SLACK_WEBHOOK` environment variable
- I have added the `SLACK_ACCESS_TOKEN` environment variable
- I have added the `SLACK_DEFAULT_CHANNEL` environment variable
- I added the chat:write and files:write permissions for the OAuth Bot Token scope
- These are the last steps in my job: 
```
      - slack/notify:
          channel: circleci-deployments
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: circleci-deployments
          event: pass
          template: success_tagged_deploy_1
```
- The step successfully passes in CircleCI: https://app.circleci.com/pipelines/bitbucket/joelng/gotsurge-frontend-fork/14/workflows/fec1f5cc-0966-424c-ac2e-b76803ed9262/jobs/38
- Sending a curl to the webhook works:
```
curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/xxxxxxxx
```

But after all that, I still get no notifications from CircleCI

## Expected behavior:

A notification should be sent to my Slack channel

## Additional Information:

Screenshots of proof:
![Screenshot 2020-10-20 150618](https://user-images.githubusercontent.com/4394614/96552198-045e5080-12e6-11eb-9754-4ece73a89d1e.png)
![Screenshot 2020-10-20 150649](https://user-images.githubusercontent.com/4394614/96552393-47b8bf00-12e6-11eb-9f0d-fa34de1a7272.png)
![Screenshot 2020-10-20 151010](https://user-images.githubusercontent.com/4394614/96552508-6d45c880-12e6-11eb-86b0-dcc0aac3fe50.png)

![Screenshot 2020-10-20 150630](https://user-images.githubusercontent.com/4394614/96552219-0a543180-12e6-11eb-9269-dab1d565cf6c.png)

![Screenshot 2020-10-20 150701](https://user-images.githubusercontent.com/4394614/96552217-09bb9b00-12e6-11eb-83b7-22b8843269a5.png)
