### ISSUE TITLE
invalid auth silently succeeds

### ISSUE THREAD

**Issue by alexjurkiewicz** [CircleCI-Public/slack-orb#205]
## Orb version:

4.1.1

## What happened:

CircleCI config (in a workflow):

```yaml
      - slack/on-hold:
          context: kounta-slack # contains SLACK_ACCESS_TOKEN
          channel: "#redacted"
          requires:
            - plan
```
Job log output:
```plain
Checking For JQ + CURL: Debian
Sending Notification
Sending to Slack Channel: #redacted
{
  "ok": false,
  "error": "invalid_auth"
}
```

The job succeeded.

## Expected behavior:

Job should fail.
