### ISSUE TITLE
Ability to de-duplicate custom pass/fail messages

### ISSUE THREAD

**Issue by alexjurkiewicz** [CircleCI-Public/slack-orb#206]
## Describe Request:

I would like to use the same custom template with one word changed if the job succeeded or failed. Currently I have to define the step twice. It would be nice to have a better UI for this

## Examples:

```yaml
      - slack/notify:
          event: pass
          channel: "#mychannel"
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Deployment to *<< parameters.deployment_name >>* passed!"
                  }
                }
              ]
            }
      - slack/notify:
          event: fail
          channel: "#mychannel"
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Deployment to *<< parameters.deployment_name >>* failed!"
                  }
                }
              ]
            }
```

## Proposed

Some way to combine these steps into a single one. For example:

```yaml
      - slack/notify:
          event: always
          channel: "#mychannel"
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Deployment to *<< parameters.deployment_name >>* %EVENT%!"
                  }
                }
              ]
            }
```

## Supporting Documentation Links:
