### ISSUE TITLE
Slack Orb can not find the channel

### ISSUE THREAD

**Issue by as-gennadiy-n** [CircleCI-Public/slack-orb#207]
## Orb version: 

4.1.1, 4.0.3

## What happened:

Slack Orb can not find the channel specified in .circleci/config.yml or $SLACK_DEFAULT_CHANNEL environment variable. We are using project environment variables.

The behavior is the same all the time. The Slack Orb could not find the channel:
```
Checking For JQ + CURL: Debian
Sending Notification
Sending to Slack Channel: ***********
{
  "ok": false,
  "error": "channel_not_found"
}
```

## Expected behavior:

The message is sent to the channel

## Additional Information:

The $SLACK_DEFAULT_CHANNEL is present and set up as described here: https://github.com/CircleCI-Public/slack-orb/wiki/How-to-set-Slack-channel
I even tried to ad a leading `C` symbol - does not work either.

The $SLACK_ACCESS_TOKEN is present and valid. The Slack application is set up as described here: https://github.com/CircleCI-Public/slack-orb/wiki/Setup
The application is added to the private channel I try to send the message to.

The notification in the config.yml is set up like this:
```
version: 2.1 # use CircleCI 2.1

orbs:
  slack: circleci/slack@4.1.1

executors:
  .....

commands: # a collection of executable commands
  ......

jobs:
  build:
      .......

  staging-deployment:
    executor: deploy-executor
    steps:
      - checkout
      - install-awscli
      - run-deploy:
          environment: "staging"
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2.1
  GAS_Workflow:
    jobs:
      - build
      - staging-deployment:
          filters:
            branches:
              only: staging
          requires:
            - build
```

Here's a link to the circleci/slack@4.0.3 job with both the environment variable and the config specifying the channel (the config specifies channel name, and the env variable - channel ID):
https://app.circleci.com/pipelines/github/jpmobiletanaka/google_ads_service/509/workflows/cca90638-1b21-4a21-93db-23475584857a/jobs/557

Here's a link to circleci/slack@4.1.1 job with just env variable specifying Slack channel ID:
https://app.circleci.com/pipelines/github/jpmobiletanaka/google_ads_service/506/workflows/38187872-53fe-49ae-a1fe-07614e130f50/jobs/549

**Comment by as-gennadiy-n** [comment]
Hey, guys! Did you have an opportunity to look into this issue?

**Comment by KyleTryon** [comment]
> Hey, guys! Did you have an opportunity to look into this issue?
> @KyleTryon

Hello @as-gennadiy-n We, unfortunately, had not had a moment to take a look at this yet / nor have we received any more reports of this happening as of yet. We will investigate as soon as possible.

In the meantime, can you confirm you have obtained a channel name the following way:

1. Right-click the desired channel name from the slack application.
2. Click the "copy link" context menu item.
3. You should now have a link in your clipboard that resembles one of the following:
    * `https://circleci.slack.com/archives/CEX000XX0`
    * `https://circleci.slack.com/archives/G0000XXXXX0`
4. The channel name should be the string after `/archives/`. Example: `CEX000XX0`

**Second:**

Can you confirm for us, is the channel in this case a private channel? If so, please try first adding the bot to the channel via invite.

**Comment by as-gennadiy-n** [comment]
@KyleTryon Thanks a lot for you answer! 
Yes, I obtained the channel name as you described. 
Yes, the channel is private. 
Yes, the bot was added to the channel beforehand.

**Comment by ryanburr** [comment]
I am running into the same issue, though the channel I am trying to send to is public. I only see this error when using the `template` prop. If I copy and paste the template directly into the `custom` prop, it works just fine.

**Comment by adamrhunter** [comment]
for those interested, I resolved this issue by adding the app to my private channel by:

1) clicking the (i) icon, top right of slack desktop app
2) clicking the "..." more icon, most right off top options
3) clicking "add apps" and then select the slack app from the list by clicking "add"

after that, the notification worked (using default templates)

**Comment by ryanburr** [comment]
I should also clarify that I only see this issue using a custom template. If I switch to a built-in template, i.e. `basic_fail_1`, the notification sends just fine to the channel.

**Comment by as-gennadiy-n** [comment]
@adamrhunter Thanks a lot for the tip. My application was added to the private channel in some other way. I did not add a bot there. 
@KyleTryon It totally solved my issue. Works great with templates or custom messages.

**Comment by ryanburr** [comment]
@as-gennadiy-n Can you clarify if you were able to get it to work with a [dynamic template](https://github.com/CircleCI-Public/slack-orb/wiki/Dynamic-Templates) or if you are using one of the [built-in templates](https://github.com/CircleCI-Public/slack-orb/wiki#templates)?

I am still running into this `channel_not_found` error when trying to send a message with a dynamic template to a public channel.

**Comment by ryanburr** [comment]
So I figured out my issue. I had a command in my config to download a custom template, export that to an env var, and use that as my dynamic template. I then use my `notify_failure` command at the end of my jobs.
```yml
commands:
  notify_failure:
    description: Notifies slack of a job failure
    steps:
      - run:
          name: Load Slack template
          command: |
            curl https://cdn.mydomain.com/slack-templates/failed-build-template.json -o ~/tmp/templates/failed-build-template.json --create-dirs && \
            echo 'export FAILED_BUILD_TEMPLATE=$(cat ~/tmp/templates/failed-build-template.json)' >> $BASH_ENV
      - run: 
          name: Print Slack template
          command: |
            echo "Template: $FAILED_BUILD_TEMPLATE"
      - slack/notify:
          event: fail
          template: FAILED_BUILD_TEMPLATE
# ...

jobs:
  setup:
    description: Custom job
    steps:
      - checkout
      - run:
          name: Custom job command
          command: echo "This is my job"
      - notify_failure
```

If the "Custom job command" failed in my "Custom job", the "Load slack template" and "Print slack template" steps in `notify_failure` never get called since CircleCI defaults to `when: on_success`, and the `slack/notify` command prints the `channel_not_found` error.

Adding the following to my steps resolves the issue
```yml
commands:
  notify_failure:
    description: Notifies slack of a job failure
    steps:
      - run:
          when: on_fail # <-- Need to run this on failure to ensure template is loaded.
          name: Load Slack template
          command: |
            curl https://cdn.signalapis.com/slack-templates/failed-build-template.json -o ~/tmp/templates/failed-build-template.json --create-dirs && \
            echo 'export FAILED_BUILD_TEMPLATE=$(cat ~/tmp/templates/failed-build-template.json)' >> $BASH_ENV
      - run: 
          when: on_fail
          name: Print Slack template
          command: |
            echo "Template: $FAILED_BUILD_TEMPLATE"
      - slack/notify:
          event: fail
          template: FAILED_BUILD_TEMPLATE
```

That being said, can we add some better error messaging if the `template:` provided does not exist?
