### ISSUE TITLE
Windows support not working in version 4

### ISSUE THREAD

**Issue by tom-james-watson** [CircleCI-Public/slack-orb#208]
## What happened:

Based on discussion in https://github.com/CircleCI-Public/slack-orb/issues/145, we upgrade our slack orb usage to version 4.

We have a job that runs on the windows executor:

```
  <job name>:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      ...
      - slack/notify:
          channel: <channel id>
          event: fail
          template: basic_fail_1
```

What we see is:

```
At line:1 char:18
+ BuildMessageBody() {
+                  ~
An expression was expected after '('.
At line:6 char:7
+     if [ -n "$SLACK_PARAM_CUSTOM" ]; then
+       ~
Missing '(' after 'if' in if statement.
At line:6 char:9
+     if [ -n "$SLACK_PARAM_CUSTOM" ]; then
+         ~
Missing type name after '['.
At line:26 char:13
+ PostToSlack() {
+             ~
An expression was expected after '('.
At line:31 char:8
+     for i in $(eval echo \""$SLACK_PARAM_CHANNEL"\" | sed "s/,/ /g")
+        ~
Missing opening '(' after keyword 'for'.
At line:32 char:7
+     do
+       ~
Missing statement body in do loop.
At line:37 char:11
+         --data \
+           ~
Missing expression after unary operator '--'.
At line:37 char:11
+         --data \
+           ~~~~
Unexpected token 'data' in expression or statement.
At line:37 char:15
+         --data \
+               ~
The Data section is missing its statement block.
At line:38 char:27
+ ...      "$SLACK_MSG_BODY" https://slack.com/api/chat.postMessage | jq '{ ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'https://slack.com/api/chat.postMessage' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression
 

Exited with code exit status 1
```

## Expected behavior:

For the notification to be sent successfully, like it is on the linux and macOS executors.

**Comment by gmemstr** [comment]
This orb was built with POSIX-compliance in mind, and it's tricky to support both Windows powershell and bash in the same breath. @KyleTryon has a bit more insight on this, but while we make best effort to ensure things are compatible, supporting powershell is hard when we're trying to make the command equally compatible with Linux/macOS (although there are some (admittedly inelegant) ways around it).

**Comment by KyleTryon** [comment]
It is absolutely something we want to achieve in the short term, though this functionality is not yet expected at the moment. When we do implement this, it will be using Bash on windows. At the moment there is a bug on CircleCI in where the bash-on-windows output is not visible within the UI output. Theoretically, this should be fine, the orb should still be working under the hood, but this bug makes it very difficult to test/debug this functionality.

I think it may be worth leaving this issue open to collect information/opinions and such.

**Comment by tom-james-watson** [comment]
Yeah, I believe it's possible to specify `shell: bash.exe` for individual jobs, so that's what I had been expecting would be the case for windows support. If the plan is to eventually support this then I would leave this open as a feature request so people can track it.

**Comment by Kurt-von-Laven** [comment]
This would be great to have. In the meantime, would it be feasible to make the error message less cryptic? This is what I saw in CircleCI when I tried to use slack/notify in version 4.3.1 of the Slack orb on Windows.

```
At line:1 char:18
+ BuildMessageBody() {
+                  ~
An expression was expected after '('.
At line:6 char:7
+     if [ -n "$SLACK_PARAM_CUSTOM" ]; then
+       ~
Missing '(' after 'if' in if statement.
At line:6 char:9
+     if [ -n "$SLACK_PARAM_CUSTOM" ]; then
+         ~
Missing type name after '['.
At line:26 char:13
+ PostToSlack() {
+             ~
An expression was expected after '('.
At line:31 char:8
+     for i in $(eval echo \""$SLACK_PARAM_CHANNEL"\" | sed "s/,/ /g")
+        ~
Missing opening '(' after keyword 'for'.
At line:32 char:7
+     do
+       ~
Missing statement body in do loop.
At line:37 char:11
+         if [ ! "$SLACK_ERROR_MSG" = "null" ]; then
+           ~
Missing '(' after 'if' in if statement.
At line:37 char:13
+         if [ ! "$SLACK_ERROR_MSG" = "null" ]; then
+             ~
Missing type name after '['.
At line:43 char:15
+             if [ "$SLACK_PARAM_IGNORE_ERRORS" = "0" ]; then
+               ~
Missing '(' after 'if' in if statement.
At line:43 char:17
+             if [ "$SLACK_PARAM_IGNORE_ERRORS" = "0" ]; then
+                 ~
Missing type name after '['.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression
 

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by amot3st** [comment]
I also second this. Having support for powershell is very important for some projects that depend on that.

**Comment by Kurt-von-Laven** [comment]
You can use build artifacts to pass the outcome of a job from a Windows workflow to a Linux workflow and then trick the Slack orb into reporting the status of the Windows workflow from the Linux workflow by overriding the environment variables it reads from. This is a very ugly solution, but I personally prefer it to having no Slack notifications at all on Windows. Another option would be to ditch the Slack orb altogether and hit the Slack API directly. Any feedback folks have on improving this workaround is quite welcome.

```
version: 2.1
orbs:
  slack: circleci/slack@4.4.0
  windows: circleci/windows@2.4.0
jobs:
  build:
    executor: windows/default
    steps:
      - run:
          name: Make directory for job metadata.
          command: mkdir C:/tmp/job_metadata
          shell: bash.exe
      - run:
          name: Write current job URL.
          command: echo "$CIRCLE_BUILD_URL" > C:/tmp/job_metadata/build_url.txt
          shell: bash.exe
...
      - run:
          when: on_fail
          name: Write job exit code 1 for failure.
          command: echo 1 > C:/tmp/job_metadata/exit_code.txt
          shell: bash.exe
      - run:
          when: on_success
          name: Write job exit code 0 for success.
          command: echo 0 > C:/tmp/job_metadata/exit_code.txt
          shell: bash.exe
      - store_artifacts:
          path: /tmp/job_metadata
          destination: build-job-metadata
  notify:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          name: Download any job metadata artifacts for latest completed job on this branch.
          command: >
            curl
            --header "Content-Type: application/json"
            --header "Accept: application/json"
            --header "Circle-Token: $CIRCLE_TOKEN"
            "https://circleci.com/api/v1.1/project/<< pipeline.project.type >>/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/latest/artifacts?branch=$CIRCLE_BRANCH&filter=completed" |
            grep --only-matching 'https://[^"]*build-job-metadata[^"]*' |
            xargs -I url wget --header "Circle-Token: $CIRCLE_TOKEN" url
      - run:
          name: Overwrite CIRCLE_JOB environment variable with build.
          command: echo export CIRCLE_JOB=build >> $BASH_ENV
      - run:
          name: Overwrite CIRCLE_BUILD_URL environment variable from prior job metadata.
          command: echo export CIRCLE_BUILD_URL=$(<build_url.txt) >> $BASH_ENV
      - run:
          name: Exit with code from prior job metadata.
          command: exit $(<exit_code.txt)
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
workflows:
  build:
    jobs:
      - build
  # Take advantage of the fact that free CircleCI accounts are limited to
  # running one workflow at a time. If you are on a paid account, these
  # workflows will instead run in parallel. Consider submitting a pull request
  # to the Slack orb to use the bash.exe shell on Windows, using
  # https://github.com/eddiewebb/circleci-queue, or using the CircleCI API to
  # wait for the build workflow to complete.
  notify:
    jobs:
      - notify:
          context:
            # a context that defines the CIRCLE_TOKEN environment variable
            # to be a CircleCI API token for your project with Admin scope
            - circleci-api-admin
            # a context that defines the SLACK_ACCESS_TOKEN and SLACK_DEFAULT_CHANNEL
            # environment variables as specified by
            # https://github.com/CircleCI-Public/slack-orb#readme
            - slack
```

**Comment by gmemstr** [comment]
At this point, the only "real" solution is a seperate command when using Windows/PowerShell, which isn't ideal but is really our only option given the fact there's (as far as I can tell) no way to write both valid bash and PowerShell in the same script.

**Comment by Kurt-von-Laven** [comment]
I would like to challenge the notion that PowerShell support is important. Windows support is important, and the Windows image ships with bash. I believe the simplest solution would be to permit a default shell to be specified consistently on all platforms. The Slack orb is not the only orb that would benefit from this.

In the meantime, here is a better workaround. It turns out the use of artifacts is unnecessary, and it's risky to assume that the most recent completed job on the same branch is the correct job to report the status of. A better solution is to search for the most recent completed job with the same commit hash using the CircleCI API. This also enables propagation of cancellations to the notify job. Put the following code in .circleci/trickSlackOrb.sh:

```bash
#!/bin/bash

set -eufo pipefail

# Issues a v1.1 CircleCI API request to the given relative path within this
# project, and outputs the JSON response to stdout. Specify the HTTP request
# method as the second argument. CIRCLE_TOKEN is not a CircleCI built-in and
# must be provided by a context. It must be a CircleCI API token with access to
# this project and the required scope. The environment variable VCS_TYPE is not
# a CircleCI built-in and should be set from the CircleCI config.yml file to
# << pipeline.project.type >>. See
# https://circleci.com/docs/2.0/pipeline-variables/#pipeline-values.
makeApiRequest() {
  curl \
    --request "$2" \
    --header "Content-Type: application/json" \
    --header "Accept: application/json" \
    --header "Circle-Token: $CIRCLE_TOKEN" \
    "https://circleci.com/api/v1.1/project/$VCS_TYPE/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$1"
}

# Output the value of the given JSON key to stdout. The second parameter is the
# JSON string to search.
getJsonValue() {
  local match="$(grep --only-matching "\"$1\"\s*:\s*\"[^\"]*\"" <<< "$2")"
  # Get the value between the third and fourth double quotes.
  cut --delimiter=\" --fields=4 <<< "$match"
}

# Trick the Slack orb into reporting the status of the most recently completed
# job preceding this one that has the same VCS commit hash. Fail this job if the
# preceding one failed. Cancel this job if the preceding one was cancelled.
# Overwrite the CIRCLE_JOB environment variable with the prior job's name and
# the CIRCLE_BUILD_URL environment variable with the prior job's URL. The other
# CIRCLE_* environment variables that Slack reads from should be the same
# between this notify job and the corresponding prior job. If no corresponding
# job can be found, fail this job without tricking Slack.
trickSlackOrb() {
  local buildNum
  for ((buildNum = $CIRCLE_BUILD_NUM - 1; buildNum > 0; buildNum--))
  do
    # This API request requires that CIRCLE_TOKEN have at least the read only
    # scope. See https://circleci.com/docs/api/v1/#single-job.
    local jobMetadata="$(makeApiRequest "$buildNum" "GET")"

    local job="$(getJsonValue "CIRCLE_JOB" "$jobMetadata")"
    if [[ "$job" != "notify" ]] &&
      grep --quiet "\"vcs_revision\":\"$CIRCLE_SHA1\"" <<< "$jobMetadata" &&
      grep --quiet '"lifecycle":"finished"' <<< "$jobMetadata" &&
      grep --quiet '"dont_build":null' <<< "$jobMetadata"
    then
      if grep --quiet '"outcome":"canceled"' <<< "$jobMetadata"
      then
        # Cancels the currently executing CircleCI job, and outputs a JSON document
        # containing metadata regarding this job to stdout. See
        # https://circleci.com/docs/api/v1/#cancel-a-build. This API request
        # requires that CIRCLE_TOKEN token have the admin scope.
        makeApiRequest "$CIRCLE_BUILD_NUM/cancel" "POST"
        # Give the cancellation up to a minute to take effect before failing.
        sleep 60
        break
      fi
      local buildUrl="$(getJsonValue "build_url" "$jobMetadata")"
      echo "export CIRCLE_JOB=$job" >> $BASH_ENV
      echo "export CIRCLE_BUILD_URL=$buildUrl" >> $BASH_ENV
      grep --quiet '"outcome":"success"' <<< "$jobMetadata" && return
      break
    fi
  done
  exit 1
}

trickSlackOrb
```

Include an extra job in your .circleci/config.yml that runs the script and issues the Slack notification:

```yaml
version: 2.1
orbs:
  slack: circleci/slack@4.4.2
  windows: circleci/windows@2.4.0
jobs:
  build:
    executor: windows/default
    steps:
...
  notify:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Trick the Slack orb into reporting the status of the most recently finished preceding build job.
          command: source .circleci/trickSlackOrb.sh
          environment:
            VCS_TYPE: << pipeline.project.type >>
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
workflows:
  build:
    jobs:
      - build
  # Take advantage of the fact that free CircleCI accounts are limited to
  # running one workflow at a time. If you are on a paid account, these
  # workflows will instead run in parallel. Consider submitting a pull request
  # to the Slack orb to use the bash.exe shell on Windows, using
  # https://github.com/eddiewebb/circleci-queue, or using the CircleCI API to
  # wait for the build workflow to complete.
  notify:
    jobs:
      - notify:
          context:
            # a context that defines the CIRCLE_TOKEN environment variable
            # to be a CircleCI API token for your project with Admin scope
            - circleci-api-admin
            # a context that defines the SLACK_ACCESS_TOKEN and SLACK_DEFAULT_CHANNEL
            # environment variables as specified by
            # https://github.com/CircleCI-Public/slack-orb#readme
            - slack
```
