### ISSUE TITLE
Dynamic Template Parse Error

### ISSUE THREAD

**Issue by ryanburr** [CircleCI-Public/slack-orb#209]
## Orb version:

4.1.1

## What happened:

When trying to use the `template` property for a [dynamic template](https://github.com/CircleCI-Public/slack-orb/wiki/Dynamic-Templates), I am met with the following error.

```
Checking For JQ + CURL: Debian
parse error: Invalid numeric literal at line 2, column 0

Exited with code exit status 4
CircleCI received exit code 4
```

When I copy and paste this same template into the `custom` field, it works just fine.

## Expected behavior:

Using the same template from the `custom` property as a dynamic template should yield the same result.

## Additional Information:

Unfortunately, the repo I am working in is private, but here is the template/configuration I'm working with.

`config.yml`
```yml
    steps:
      - attach_workspace:
          at: ~/tmp # contains the .json file with the template
      - run: 
          name: Source bash env
          command: source $BASH_ENV
      - run: 
          name: Print Slack template
          command: cat $FAILED_BUILD_TEMPLATE
      - slack/notify:
          event: fail
          template: FAILED_BUILD_TEMPLATE
```

`cat $FAILED_BUILD_TEMPLATE`
```json
{
  "blocks": [
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": ":x: Failed: ${CIRCLE_USERNAME}'s job <${CIRCLE_BUILD_URL}|${CIRCLE_JOB}>"
      }
    },
    {
      "type": "context",
      "elements": [
        {
          "type": "mrkdwn",
          "text": "${CIRCLE_PROJECT_REPONAME} • ${CIRCLE_BRANCH}"
        }
      ]
    },
    {
      "type": "actions",
      "elements": [
        {
          "type": "button",
          "text": {
            "type": "plain_text",
            "text": "View Workflow"
          },
          "url": "https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}"
        },
        {
          "type": "button",
          "text": {
            "type": "plain_text",
            "text": "View Job"
          },
          "url": "${CIRCLE_BUILD_URL}"
        },
        {
          "type": "button",
          "text": {
            "type": "plain_text",
            "text": "View Commit"
          },
          "url": "https://github.com/signaldevs/${CIRCLE_PROJECT_REPONAME}/commit/${CIRCLE_SHA1}"
        }
      ]
    }
  ]
}
```
