### ISSUE TITLE
Slack notification on failure only delivered when event set to always

### ISSUE THREAD

**Issue by adamhartley** [CircleCI-Public/slack-orb#216]
## Orb version: 4.1.2

Slack notification snippet from `config.yml`:
```
      - slack/notify:
          branch_pattern: develop,master
          event: fail
          template: basic_fail_1
```

## What happened:
On CircleCI build failure, Slack notification only appears when `event: always` is set, and does not appear on build failure when `event: fail` is set. 

## Expected behavior:
On CircleCI build failure, Slack notification of build failure should appear when `event: fail` is set.
