### ISSUE TITLE
Passing custom template as env var or parameter causes JSON error

### ISSUE THREAD

**Issue by chrisbruford** [CircleCI-Public/slack-orb#219]
## What happened:

Passing valid JSON directly into the `custom` parameter works as expected; however when putting said JSON into an environment variable or parameter it causes a parse error.

I've tried:

Passing the JSON directly ✅
Passing the JSON as an env var ❌
Passing the JSON as a string parameter ❌
Passing the JSON as an env var parameter ❌

Here's how I'm setting and calling (the node call returns the JSON in question):

```
- run:
    name: Generate slack failure message
    when: always
    command: |
      echo "export SLACK_FAILURE_MSG='`node repo/slack-on-fail $CIRCLE_BUILD_URL`'" >> $BASH_ENV
- slack-custom:
    event: always
    template: SLACK_FAILURE_MSG
```

Here's the command I've setup:

```
slack-custom:
    parameters:
      template:
        type: env_var_name
        default: SLACK_FAILURE_MSG
      event:
        type: string
        default: always
    steps:
      - run:
          name: Show template
          command: |
            echo ${<<parameters.template>>}
      - slack/notify:
          custom: ${<<parameters.template>>}
          event: "<<parameters.event>>"
```

The "Show template" step runs as expected and outputs the valid JSON

here's the output from the slack/notify step:

```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (***********)
It appears you have a Slack Webhook token present in this job.
Please note, Webhooks are no longer used for the Slack Orb (v4 +).
Follow the setup guide available in the wiki: https://github.com/CircleCI-Public/slack-orb/wiki/Setup
Posting Status
Checking For JQ + CURL: Debian
34 packages can be upgraded. Run 'apt list --upgradable' to see them.
The following additional packages will be installed:
  libjq1 libonig5
The following NEW packages will be installed:
  jq libjq1 libonig5
0 upgraded, 3 newly installed, 0 to remove and 34 not upgraded.
Need to get 313 kB of archives.
After this operation, 1062 kB of additional disk space will be used.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "***********",
	LANG = "***********"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libonig5:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 58731 files and directories currently installed.)
Preparing to unpack .../libonig5_6.9.4-1_amd64.deb ...
Unpacking libonig5:amd64 (6.9.4-1) ...
Selecting previously unselected package libjq1:amd64.
Preparing to unpack .../libjq1_1.6-1_amd64.deb ...
Unpacking libjq1:amd64 (1.6-1) ...
Selecting previously unselected package jq.
Preparing to unpack .../archives/jq_1.6-1_amd64.deb ...
Unpacking jq (1.6-1) ...
Setting up libonig5:amd64 (6.9.4-1) ...
Setting up libjq1:amd64 (1.6-1) ...
Setting up jq (1.6-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
parse error: Invalid numeric literal at line 1, column 2
parse error: Invalid numeric literal at line 1, column 2

Exited with code exit status 4
```

## Expected behavior:

The slack/notify command should be able to receive  env vars and params in the custom parameter
