### ISSUE TITLE
Mentions don't trigger notification

### ISSUE THREAD

**Issue by montanaflynn** [CircleCI-Public/slack-orb#227]
## What happened:

When a job fails it doesn't trigger slack notifications for those in the mentions

## Expected behavior:

Anyone mentioned gets a slack notification.

## Additional Information:

When a job fails with the following config I see my name as plain text in the mentioned section but don't get a slack notification. 

```
      - slack/notify:
          event: fail
          mentions: '@montanaflynn'
          template: basic_fail_1
```

It's also not clickable:

<img width="144" alt="Screen Shot 2021-01-13 at 13 06 36" src="https://user-images.githubusercontent.com/24260/104413756-7ff83280-55a1-11eb-9ced-804485349589.png">
