### ISSUE TITLE
Implement Dynamic Custom Templates processing

### ISSUE THREAD

**Issue by zumby** [CircleCI-Public/slack-orb#246]
## Describe Request:

There is no way to **centrally manage custom templates** at the moment.

Users may want this hard:
- store custom templates in 1 place
- manage them only in that place only
- refer to templates (reuse) in many pipelines

Please implement something like **dynamic custom templates processing**

## Examples:

```
version: 2.1
orbs:
  slack: circleci/slack@4.3.0
executors:
  cimg-base:
    docker:
      - image: cimg/base:stable
    resource_class: small
workflows:
  version: 2.1
  WF1:
    jobs:
      - JOB1:
          filters:
            branches:
              only:
                - /tst-slack-notify/
          context:
            - SLACK
jobs:
  JOB1:
    executor: cimg-base
    steps:
      - run: echo 'hello'
      - slack/notify:
          event: pass
          channel: 'C0XXXXXXXFR'
          custom: $(curl -s https://raw.githubusercontent.com/CircleCI-Public/slack-orb/master/src/message_templates/basic_success_1.json)

```
If you try to use a template that is fetched, i.e by Curl, you'll get the error message:
Im no expert, but looks like it has something to do with how you process template with JQ and how the template is being passed to your script notify.sh

![image](https://user-images.githubusercontent.com/26290616/109544373-28217680-7ad0-11eb-8f1d-a60416ee9691.png)
