### ISSUE TITLE
Handle Build Error to notify the error to slack

### ISSUE THREAD

**Issue by kamillle** [CircleCI-Public/slack-orb#247]
## Describe Request:

I want slack-orb to handle Build Error that caused by invalid yaml syntax etc to notify the error to slack. I imagine the webhook style notification like below image.
![image](https://user-images.githubusercontent.com/32205171/110193436-362c1a00-7e77-11eb-8fd7-3b908d67770f.png)

Let me know how to do this if this orb already supports the error handling 🙇 

## Examples:

```yaml
version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
        # this causes syntax error
        event: pass 
          template: basic_success_1

workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
```

## Supporting Documentation Links:

N/A
