### ISSUE TITLE
Cannot get circleci/slack@4.1 to Work. invalid_arguments error

### ISSUE THREAD

**Issue by bytekast** [CircleCI-Public/slack-orb#255]
## Orb version:

This does not work
```
- slack/notify:
     event: pass
     template: basic_success_1
- slack/notify:
     event: fail
     template: basic_fail_1
```

I've tried setting the `channel` property above or a `SLACK_DEFAULT_CHANNEL` environment variable in the context. 

## What happened:

```
Posting Status
Checking For JQ + CURL: Debian
Sending to Slack Channel: *********
{
  "ok": false,
  "error": "invalid_arguments"
}
```

## Expected behavior:

Notification should be sent.

## Additional Information:

It would be helpful to add logging to help debug this.
