### ISSUE TITLE
Mentions do not send an alert to the Slack ID provided

### ISSUE THREAD

**Issue by danishs81** [CircleCI-Public/slack-orb#263]
## Orb version:
4.4.0

## What happened:
Following is my code in config.yml

```
- slack/notify:
          event: fail
          mentions: '<@user name>, @userName'
          template: basic_fail_1
```
the slack message shows the Mentions; however, does not ping the users mentioned in the `mentions` block
