### ISSUE TITLE
parse error: Invalid numeric literal at line 2, column 0

### ISSUE THREAD

**Issue by dotCipher** [CircleCI-Public/slack-orb#271]
## Orb version:

4.4.2

## What happened:

Sending notification caused command to exit without sending, output from job log is:
```
Posting Status
Checking For JQ + CURL: Debian
parse error: Invalid numeric literal at line 2, column 0
parse error: Invalid numeric literal at line 2, column 0

Exited with code exit status 4
```
## Expected behavior:

Success message should post into channel `ABC`

## Additional Information:

Command config that failed:
```
      - slack/notify:
          channel: ABC
          branch_pattern: main
          event: always
          custom: basic_success_1
```

Using image: `cimg/openjdk:14.0.2-node` for the job
