### ISSUE TITLE
Defining branch_pattern sends notifications from tag workflows

### ISSUE THREAD

**Issue by brandon-leapyear** [CircleCI-Public/slack-orb#272]
## Orb version:

4.3.3

## What happened:

we have a step defined like:
```yaml
- slack/notify:
    branch_pattern: master
    event: fail
    template: basic_fail_1
    channel: nightly-builds-notifications
```
where we want ONLY workflows kicked off by running the master branch to send notifications. What happened was we had a workflow kicked off from a git tag and the notification got sent from that workflow.

It seems like this behavior comes from the first line in `FilterBy`:
```bash
if [[ -z "$1" ]] || [[ -z "$2" ]];
  return
fi
```

## Expected behavior:

If I define a `branch_pattern`, it should ONLY send the notification if the workflow was kicked off by a branch AND the branch matches the pattern. Likewise, if I define a `tag_pattern`, it should ONLY send the notification if the workflow was kicked off by a git tag AND the tag matches the pattern.

I'd expect behavior more like
```diff
 FilterBy() {
-    if [ -z "$1" ] || [ -z "$2" ]; then
-      return
-    fi
 
     ...
 }
 
 ShouldPost() {
     if [ "$CCI_STATUS" = "$SLACK_PARAM_EVENT" ] || [ "$SLACK_PARAM_EVENT" = "always" ]; then
         # In the event the Slack notification would be sent, first ensure it is allowed to trigger
         # on this branch or this tag.
-        FilterBy "$SLACK_PARAM_BRANCHPATTERN" "${CIRCLE_BRANCH:-}"
-        FilterBy "$SLACK_PARAM_TAGPATTERN" "${CIRCLE_TAG:-}"
+        if [[ -n "${CIRCLE_BRANCH:-}" ]]; then
+            FilterBy "$SLACK_PARAM_BRANCHPATTERN" "$CIRCLE_BRANCH"
+        elif [[ -n "${CIRCLE_TAG:-}" ]]; then
+            FilterBy "$SLACK_PARAM_TAGPATTERN" "$CIRCLE_TAG"
+        else
+            # deduplicate logic in else block
+            exit 0
+        fi
 
         echo "Posting Status"
     else
         ...
     fi
 }
```

**Comment by bobbyrenwick** [comment]
This is happening to us but in reverse, we're not setting a `branch_pattern`, just a `tag_pattern` and that's causing notifications when the build is triggered by a branch

**Comment by woylie** [comment]
Same here. We'd like to have success notifications only for production releases, but with a configuration like this:

```
- slack/notify:
          event: pass
          channel: ...
          template: success_tagged_deploy_1
          tag_pattern: prod\/.+
```

We also get success notifications for deployments triggered by merging to our stage branch (without a tag).
