### ISSUE TITLE
Allow providing a custom message from an external file

### ISSUE THREAD

**Issue by OrBin** [CircleCI-Public/slack-orb#274]
## Describe Request:
Please allow providing a custom message from an external file, in addition to the ability to inline it.

## Examples:
If this feature was implemented, the `custom_notification` [example from the Orb registry](https://circleci.com/developer/orbs/orb/circleci/slack#usage-custom_notification) would look like this:
```yaml
version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom_notification_filename: custom_notification.json # <-- Here
          event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets

```

## Supporting Documentation Links:
N/A
