### ISSUE TITLE
parse error: Invalid numeric literal at line 1, column 7

### ISSUE THREAD

**Issue by mimozell** [CircleCI-Public/slack-orb#289]
## Orb version:
slack: circleci/slack@4.4.2

## What happened:
The code that I am using:
```
    jobs:
      - slack/on-hold:
          name: approve plan before apply
          context: platform-slack
          custom: 'Please approve terraform plan before apply'
          requires:
            - 'previous job'
```
Posting to Slack failed. Context is set up correctly.
![Screenshot 2021-08-02 at 15 54 30](https://user-images.githubusercontent.com/40452559/127873484-33e90652-2f41-4aa3-9244-9d1c274eaad3.png)

## Expected behavior:
Expected to see the message in Slack.

## Additional Information:
```
executors:
  base:
    docker:
      - image: cimg/base:2021.07
```
