### ISSUE TITLE
single notify for success / failure?

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/slack-orb#306]
## Describe Request:
IIRC, with v 3.x of this orb, you could use the same notify for both success / failure (optionally with different messages), and without specifying a template. With the new orb, you have to use something like:

```yaml
            - slack/notify:
                event: pass
                template: basic_success_1
            - slack/notify:
                event: fail
                template: basic_fail_1
```

IMO, it would be nice to have a basic notify command (or a fallback when no template / event is passed) such that you could just have
```yaml
 - slack/notify
```

and get a basic success template on success or basic fail template on failure.

## Supporting Documentation Links:
