### ISSUE TITLE
notify command's run steps run in the default executor shell

### ISSUE THREAD

**Issue by m0sa** [CircleCI-Public/slack-orb#344]
## Orb version:

4.9.3

## What happened:

The notify command tries to execute it's bash script in the default shell. I have a executor set up as:

```
version: 2.1
orbs:
  slack: circleci/slack@4.9.3
executors:
  dotnet-windows:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.large
    shell: powershell.exe -ExecutionPolicy Bypass
jobs:
  example:
    executor: dotnet-windows
  steps:
    - slack/notify:
        ...
        # fails because the steps in the notify command do not explicitly specify `shell: bash`
```

## Expected behavior:

Command explicitly specifies it's steps should run in a bash shell.
