### ISSUE TITLE
Customizable domain for API to send message

### ISSUE THREAD

**Issue by luncliff** [CircleCI-Public/slack-orb#359]
## Describe Request:

Hi. I'm trying to use this orb(v4.9 actually). And got `invalid_auth` error.
After short survey, I found the `slack/notify` is sending message to https://slack.com/api/chat.postMessage.
We are using different domain for the Slack, It will be helpful if we can customize API server to send the message.  

## Examples:

Need some field like `api_host`.

```yaml
- slack/notify:
    circleci_host: "https://circleci.abcc.com"
    api_host: "abcc" # (optional) send to https://abcc.slack.com/api/chat.postMessage
    channel: C0123456789 
```
