### ISSUE TITLE
"error": "invalid_arguments" when using basic_success_1

### ISSUE THREAD

**Issue by ben-codexdf** [CircleCI-Public/slack-orb#360]
## Orb version: 
4.1

## What happened: 
Received "error": "invalid_arguments" in CircleCI job log. Job completed successfully, too. Using the following config:
```
      - slack/notify:
          channel: '<my_slack_channel>' 
          event: pass
          template: basic_success_1
```
## Expected behavior: 

1. We should get the correctly formatted message in our Slack
2. We should see "error": null in the CircleCI job log. 

## Additional Information:

Looks like this was previously an issue thought to have been resolved.
