### ISSUE TITLE
Show the dependent / required job and commit message

### ISSUE THREAD

**Issue by khteh** [CircleCI-Public/slack-orb#363]
## Describe Request:
Currently the slack notification message shows the name of this `slack-orb` job and commit hash value. It would be more usefule to be able to show the following:
(1) The dependent / `required` job - The real job of build and/or deployment
(2) The commit message.
## Examples:
```
workflows:
  main:
    jobs:
      - build_deploy_app1:
          name: BuildDeployApp1
          filters:
            branches:
              only:
                - staging
                - master
      - app1_notification:
          name: App1CICD
          requires:
            - BuildDeployApp1
```
It should show `BuildDeployApp1` job name and the commit message which triggered the workflow.
## Supporting Documentation Links:
