### ISSUE TITLE
Doesn't run the notification step when circleci exits with status code > 0

### ISSUE THREAD

**Issue by khteh** [CircleCI-Public/slack-orb#365]
## What happened:
I have the following workflow:
```
workflows:
  main:
    jobs:
      - build_deploy_buyer_vercel:
          name: BuildDeployBuyerVercel
          filters:
            branches:
              only:
                - staging
                - master
      - build_deploy_seller_vercel:
          name: BuildDeploySellerVercel
          filters:
            branches:
              only:
                - staging
                - master
      - buyer_notification:
          name: BuyerPlatformCICD
          requires:
            - BuildDeployBuyerVercel
      - seller_notification:
          name: SellerPlatformCICD
          requires:
            - BuildDeploySellerVercel
```
The notifications don't run at all when the `requires` step fails.

## Expected behavior:
Notify slack channel of the real status.
