### ISSUE TITLE
Version 4.12.1 `notify` doesn't work as expected on the Windows executor

### ISSUE THREAD

**Issue by liberato-whisper** [CircleCI-Public/slack-orb#387]
## Orb version:

4.12.1

## What happened:
The powershell execution of the `slack/notify` command doesn't work:
```
#!powershell.exe -ExecutionPolicy Bypass
#!/usr/bin/env sh

# Workaround for Windows Support
# For details, see: https://github.com/CircleCI-Public/slack-orb/pull/380
# shellcheck source=/dev/null
eval printf '%s' "$SLACK_SCRIPT_NOTIFY"

eval : The term 'eval' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:6 char:1
+ eval printf '%s' "$SLACK_SCRIPT_NOTIFY"
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (eval:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Exited with code exit status 1

## Expected behavior:

Notification works as expected (and does on linux executors)

## Additional Information:

Using 
```
  executor:
    name: windows/default
```

step definition is 
```
    - when:
        condition:
          equal: [ master, << pipeline.git.branch >> ]
        steps:
          - slack/notify:
              event: fail
              template: basic_fail_1
```
