### ISSUE TITLE
`event: fail` notification doesn't work?

### ISSUE THREAD

**Issue by khteh** [CircleCI-Public/slack-orb#390]
## Orb version:
4.10.1

## What happened:

```
  notification:
    docker:
      - image: "cimg/base:stable"
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1 # Never hit this even when the dependent job failed!
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  main:
    jobs:
      - build_test:
          name: BuildAndTest
          filters:
            branches:
              only:
                - staging
                - master
      - build_docker:
          name: BuildDocker
          filters:
            branches:
              only:
                - staging
                - master
          requires:
            - BuildAndTest
      - deploy_buyer:
          name: DeployBuyerPortal
          filters:
            branches:
              only:
                - staging
                - master
          requires:
            - BuildDocker
      - notification:
          context: slack-secrets
          name: BuyerPortal2.0
          requires:
            - DeployBuyerPortal

```
## Expected behavior:
Receives `basic_fail_1` slack notification when dependent job fails
