### ISSUE TITLE
Separate JSON file for custom notification templates.

### ISSUE THREAD

**Issue by apujari-hippo** [CircleCI-Public/slack-orb#393]
## Describe Request:
Currently, for the custom notification templates we add the JSON snippet with the config YAML file. 
This results in ugly formatting and linting. 

A better solution would be to have a separate JSON file inside the `.circleci` folder and just pass the name (or path) within the config YAML file.

This will make the code look much cleaning and the JSON file can be used by our other services (which are not Circle CI). 

## Supporting Documentation Links:
https://circleci.com/developer/orbs/orb/circleci/slack#usage-custom_notification

**Comment by KyleTryon** [comment]
Hey @apujari-hippo,

We can actually do this now! Though I recommend actually instead [saving your templates into a CircleCI context](https://github.com/CircleCI-Public/slack-orb/wiki/Reuse-Custom-Templates#2-create-a-context-for-your-slack-templates) so that they can be shared among multiple projects. But if you want a custom template as a separate file for a repo, that should be doable.

Try this:

```yaml
    steps:
      - slack/notify:
          event: always
          template: $(cat .circleci/slack/template.json)
          channel: ABCXYZ
```

**Comment by apujari-hippo** [comment]
I updated the code as per your instructions. But the `Send  Slack - Success` step failed.

<img width="1577" alt="Screenshot 2023-03-17 at 9 53 33 AM" src="https://user-images.githubusercontent.com/94924620/225940099-edad18fb-edd1-4f4d-89dc-46e960619cca.png">

**Comment by KyleTryon** [comment]
Apologies, it is an environment variable but we actually use a convention here that looks for a string that contains an environment value. https://github.com/CircleCI-Public/slack-orb/wiki/Reuse-Custom-Templates

I can think of maybe one way to maybe get this to work, though I have not tested it.

```yaml
    environment:
        MY_TEMPATE: $(cat .circleci/slack/template.json)
    steps:
      - slack/notify:
          event: always
          template: MY_TEMPATE
          channel: ABCXYZ
```

This _should_ get eval'd and return the template string.
