### ISSUE TITLE
`branch_pattern` not matching multiple patterns as expected (v4.1)

### ISSUE THREAD

**Issue by nikbuskirk-dh** [CircleCI-Public/slack-orb#406]
## Orb version:

4.1

## What happened:

We are using the `branch_pattern` parameter with multiple comma-delimited patterns, but the notify command is failing to match and send a Slack notification when expected.

Setup:
```yml
SLACK_TRUNK_OR_REL_BRANCH_REGEX: &SLACK_TRUNK_OR_REL_BRANCH_REGEX trunk,release\/\d{4}-\d{2}-\d{2}[a-zA-Z]*

orbs:
  slack: circleci/slack@4.1

...

      - slack/notify:
          event: fail
          template: basic_fail_1
          branch_pattern: *SLACK_TRUNK_OR_REL_BRANCH_REGEX
          channel: alert-trunk-station
```

Given:
```
branch = "release/2023-05-03"
```

Error:
```
NO SLACK ALERT

Current reference "release/2023-05-03" does not match any matching parameter
Current matching pattern: trunk,release\/\d{4}-\d{2}-\d{2}[a-zA-Z]*
CircleCI received exit code 0
```

## Expected behavior:

The `notify` command should recognize the given branch as matching one of our patterns, and send a Slack notification when our pipeline fails.

## Additional Information:

I have tried but failed to recreate the issue locally; I recreated a bash script with the `FilterBy()` function copied from source and ran some tests, but the filter seems to work as expected running locally.

I also realize we're several minor versions behind, but I haven't spotted anything in the code or release tags to indicate that there was a change to this behavior. I'm more than happy to upgrade and solve this, but without reproducing I'm wary of the upgrade not solving it.

Thanks for taking a look with me!
