### ISSUE TITLE
Slack notification fails due to CURL not being found

### ISSUE THREAD

**Issue by Phonesis** [CircleCI-Public/slack-orb#412]
We are encountering an issue with the Slack orb where it fails to send notifications with the following error: 

```
Posting Status
BASH_ENV file: /tmp/.bash_env-64787603c7b73906b9e7dc78-0-build
Does Not Exist. Skipping file execution
Checking For JQ + CURL
SLACK ORB ERROR: CURL is required. Please install
```

I have tried to install curl via npm but this doesn't seem to work. The stage we use it with uses a custom docker executor but I don't understand why this would be a problem:

```
executors:
  latest-chrome-firefox-edge:
    docker:
      - image: cypress/browsers:latest
 ```

We attach the workspace to root as follows 

```
      - attach_workspace:
          at: .
```

Any ideas what is going on?
