### ISSUE TITLE
Parse Error when sending slack notification

### ISSUE THREAD

**Issue by khaled5321** [CircleCI-Public/slack-orb#425]
## What happened:
 When I try to send notifications I get this error:  

```
Posting Status
BASH_ENV file: /tmp/.bash_env-6501b48eb4b50a2a616b6786-0-build
Exists. Sourcing into ENV
Checking For JQ + CURL
Nothing to sanitize.
parse error: Expected another key-value pair at line 9, column 9
parse error: Expected another key-value pair at line 9, column 9

Exited with code exit status 4
```

Here is my code:  
```yml
test_notification:
    machine: true
    environment:
      SLACK_ACCESS_TOKEN: token
    steps:
      - slack/notify:
            custom: |
              {
                "blocks": [
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "Test notification",
                      }
                    ]
                  }
                ]
              }
            event: always
            channel: channel name
```
