### ISSUE TITLE
parse error: Invalid numeric literal

### ISSUE THREAD

**Issue by juvarabrera** [CircleCI-Public/slack-orb#450]
## Orb version:

4.9.3

## What happened:

I'm trying to pass a custom message to slack orb. The custom message is already in json format

## Expected behavior:

Should send the message in the Slack channel

## Additional Information:

`.circleci/config.yml`
```yaml
commands:
  notify_on_e2e_fail:
    description: Send slack notification on fail
    parameters:
      channel:
        type: string
      branch_pattern:
        type: string
        default: ".+"
      message:
        type: string
        default: ""
    steps:
      - slack/notify:
          event: fail
          channel: << parameters.channel >>
          custom: << parameters.message >>
          branch_pattern: << parameters.branch_pattern >>

. . .

jobs:
  myjob:
    steps:
      . . . # some steps that creates message.txt
      - notify_on_e2e_fail:
          channel: << parameters.slack_channel >>
          message: $(cat message.txt)
```

This is the value of `message.txt`

```
{"blocks": [{"type": "header","text": {"type": "plain_text","text": ":x: E2E Test Failed","emoji": true}},{"type": "section","text": {"type": "mrkdwn","text": "*Branch*: my/branch\n\n1 tests | ✅ 0 passed | :x: 1 failures | :x: 0 errors | 🔃 0 skipped"}},{"type": "divider"},{"type": "section","text": {"type": "mrkdwn","text": "*1. Test name*"}},{"type": "section","fields": [{"type": "mrkdwn","text": "*File*: path/to/file:123\n\n*Author*: Name <email>"},{"type": "mrkdwn","text": "*View Commit*: https://github.com/org_slug/repo/commit/abcdefg\n\n*Last updated*: 2024-01-01 00:00:00 +0800 (99 days ago)"}]},{"type": "section","fields": [{"type": "mrkdwn","text": "*File*: path/to/file:123\n\n*Author*: Name <email>"},{"type": "mrkdwn","text": "*View Commit*: https://github.com/org_slug/repo/commit/abcdefg\n\n*Last updated*: 2024-01-01 00:00:00 +0800 (99 days ago)"}]},{"type": "actions","elements": [{"type": "button","text": {"type": "plain_text","text": "View CircleCI Job","emoji": true},"value": "https://circleci.com/gh/org_slug/********/1234","action_id": "actionId-0"}]}]}
```

There are no issues in the [Slack Block Kit Builder](https://app.slack.com/block-kit-builder/T40CUJ8CQ#%7B%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22:x:%20E2E%20Test%20Failed%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Branch*:%20my/branch%5Cn%5Cn1%20tests%20%7C%20%E2%9C%85%200%20passed%20%7C%20:x:%201%20failures%20%7C%20:x:%200%20errors%20%7C%20%F0%9F%94%83%200%20skipped%22%7D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*1.%20Test%20name*%22%7D%7D,%7B%22type%22:%22section%22,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22*File*:%20path/to/file:123%5Cn%5Cn*Author*:%20Name%20%3Cemail%3E%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*View%20Commit*:%20https://github.com/org_slug/repo/commit/abcdefg%5Cn%5Cn*Last%20updated*:%202024-01-01%2000:00:00%20+0800%20(99%20days%20ago)%22%7D%5D%7D,%7B%22type%22:%22section%22,%22fields%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22*File*:%20path/to/file:123%5Cn%5Cn*Author*:%20Name%20%3Cemail%3E%22%7D,%7B%22type%22:%22mrkdwn%22,%22text%22:%22*View%20Commit*:%20https://github.com/org_slug/repo/commit/abcdefg%5Cn%5Cn*Last%20updated*:%202024-01-01%2000:00:00%20+0800%20(99%20days%20ago)%22%7D%5D%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22View%20CircleCI%20Job%22,%22emoji%22:true%7D,%22value%22:%22https://circleci.com/gh/org_slug/********/1234%22,%22action_id%22:%22actionId-0%22%7D%5D%7D%5D%7D)

This is the output of Slack orb:
```
BASH_ENV file: /tmp/.bash_env-663dc3f01fdefa2f8dbddf81-0-build
Does Not Exist. Skipping file execution
Posting Status
Checking For JQ + CURL
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6

Exited with code exit status 4
```

Is this even possible? Because I tried to pass the json string manually like this and it worked.

```
      - notify_on_e2e_fail:
          channel: << parameters.slack_channel >>
          message: "{ ... }"
```

I feel like it has something to do with this specific line
```
message: $(cat message.txt)
```

I also tried 
```
message: |
  $(cat message.txt)
```

Thank you for checking 🙇

**Comment by marboledacci** [comment]
You cannot use bash in the parameters, the `$(cat message.txt)` is managed as a string and the orb is not designed to eval this.
You can get the value from a file though, you have two options:

1. Use a step before to export the content of your file to an environment variable. More information [here](https://circleci.com/docs/set-environment-variable/#set-an-environment-variable-in-a-shell-command)
2. Use include, `custom: <<include(message.txt)>>`. More information [here](https://circleci.com/docs/orb-concepts/#file-include-syntax)

**Comment by juvarabrera** [comment]
Sorry, I forgot about this issue. I've fixed it using the following

```
...
      - run:
          name: Generate E2E Error Message
          when: on_fail
          command: |
            ...
            echo 'export MESSAGE="$(cat message.json)"' >> $BASH_ENV
      - notify_on_e2e_fail: # my own command
          channel: << parameters.slack_channel >>
          template: MESSAGE
```
