### ISSUE TITLE
Notification step fails with exit code 1 and no error

### ISSUE THREAD

**Issue by yulianovdey** [CircleCI-Public/slack-orb#455]
## Orb version:
4.13.3

## What happened:
Notification step failed with exit code 1 and no error message:

![Screenshot 2024-08-20 at 4 51 35 PM](https://github.com/user-attachments/assets/ad600ff0-68ab-4298-9d2c-41bbdc337279)
## Expected behavior:
Step succeeds when there is no alert that needs to be sent.

## Additional Information:
This job is only failing on this one executor, and passing otherwise.

Executor: machine / linux

Steps:
```
steps:
  - run:
      name: Set Slack notification params on fail
      command: echo 'export SLACK_NOTIFICATION_COLOR="#FF5C5C"' >> "$BASH_ENV"
      when: on_fail
  - slack/notify:
      branch_pattern: master,main
      event: fail
      channel: <<parameters.channel>>
      custom: <<include(includes/slack-notification-template.json>>
```

Template:
```json
{
  "attachments": [
    {
      "color": "$SLACK_NOTIFICATION_COLOR",
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": "*$CIRCLE_PROJECT_REPONAME* build started by $CIRCLE_USERNAME ${CCI_STATUS}ed!"
          }
        },
        {
          "type": "context",
          "elements": [
            {
              "type": "mrkdwn",
              "text": "branch: *$CIRCLE_BRANCH* | job: *$CIRCLE_JOB*"
            }
          ]
        },
        {
          "type": "actions",
          "elements": [
            {
              "type": "button",
              "text": {
                "type": "plain_text",
                "text": "View"
              },
              "url": "$CIRCLE_BUILD_URL"
            }
          ]
        }
      ]
    }
  ]
}
```

Thank you!
