### ISSUE TITLE
v4.15.0 Release Breaking Change on default values for tag and branch patterns

### ISSUE THREAD

**Issue by cnd5041** [CircleCI-Public/slack-orb#465]
## Orb version: v4.15.0

https://github.com/CircleCI-Public/slack-orb/releases/tag/v4.15.0
https://github.com/CircleCI-Public/slack-orb/pull/462 

## What happened:

We stopped getting notifications around 9/18/2024. 

Seeing "error" message when notifying: 

```
NO SLACK ALERT

Current reference "" does not match any matching parameter
Current matching pattern: .+
```

Passes this step on CircleCI with the above message. Loose example below. This stopped working with v4.15.0

```
slack: circleci/slack@4

build: 
  steps: 
      ....
      - slack/notify:
            channel: xxxxx234234
            event: fail
            template: basic_fail_1
```

It works if I go back to `slack: circleci/slack@4.13.3`

## Expected behavior:

Message is sent to Slack. Parameters are backwards compatible and do not required changes to config.
