### ISSUE TITLE
Missing guide on how to include reference for custom template

### ISSUE THREAD

**Issue by kimyu92** [CircleCI-Public/slack-orb#470]
## Orb version:

latest

## What happened:

I didn't see any example on how to override `actions` for custom template. 

Overriding `section` is working fine but without showing ability to override actions with make it hard to associate slack message with job 

## Expected behavior:

A section in `README.md` demonstrate the behavior described above

**Comment by marboledacci** [comment]
Hello @kimyu92 I don't know what behavior are you talking about, could you give more details?
What are you doing with section that you want to do with actions.

**Comment by yaroslav-storozhik** [comment]
do you want to save some notifification like below as a template and us it multiple times in a job?
```
- slack/notify:
      event: always
      channel: engineering
      thread_id: testing
      custom: |
        {
          "blocks": [
            {
              "type": "section",
              "fields": [
                {
                  "type": "plain_text",
                  "text": "*Tests finished.*",
                  "emoji": true
                }
              ]
            }
          ]
        }
```

**Comment by kimyu92** [comment]
@marboledacci @yaroslav-storozhik 

<img width="769" alt="Image" src="https://github.com/user-attachments/assets/0e9a85eb-a7f9-4d77-9df8-063951955213" />

Using the following syntax the link can only show up as raw text only rather than "View Job" clickable button ☝ 

```yaml
      - slack/notify:
          event: << parameters.event >>
          channel: "FOO"
          mentions: "@engineers"
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "<< parameters.message >>",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
```
