### ISSUE TITLE
Conditional slack notification

### ISSUE THREAD

**Issue by mkoiev** [CircleCI-Public/slack-orb#474]
## Describe Request:
Depends on workflow I have to send slack notification to different channels or skip slack notification at all. For expample I don't need slack notification in case tests are running against dev environment otherwise I want to send notification.
It would be cool if it will be some new boolean "skip: false" or similar. 

## Examples:

      - slack/notify:
          channel: $SLACK_CHANNEL
          custom: $SLACK_MESSAGE
          mention: $QA_MENTION
          skip: << parameters.skip_slack_notification >>

      - run-tests:
          name: run-tests-against-qa
          context: SLACK_SECRET
          ENV: "qa"
          send_slack_notification: false
          requires:
            - deploy-argocd-qa
## Supporting Documentation Links:

**Comment by marboledacci** [comment]
You can use when, but not in the way you are trying.

```yaml

  - when:
        condition: <<your-condition>>
        steps:
          - slack/notify:
                channel: $SLACK_CHANNEL
                custom: $SLACK_MESSAGE
                when: << parameters.send_slack_notification >>
```
