### ISSUE TITLE
slack/status does not include mentions for custom messages

### ISSUE THREAD

**Issue by ryym** [CircleCI-Public/slack-orb#64]
### Orb version

3.2.0

### What happened

Though the `slack/status` command accepts `mentions` parameters, its notification does not include the mentions at all.

- Example build: https://circleci.com/gh/ryym/tmp-circleci-slack-orb-issue/2
- Config file: https://github.com/ryym/tmp-circleci-slack-orb-issue/blob/7e567611/.circleci/config.yml

Sample config:

```yaml
steps:
  - checkout
  - slack/status:
      success_message: OK
      mentions: ryym
```

Received message:

<img width="435" alt="tmporary___ryyms-slack_Slack" src="https://user-images.githubusercontent.com/12684251/60780203-68541880-a178-11e9-820c-f53b65c6a370.png">

### Expected behavior

It sends a message with the specified mentions, like the `slack/notify` command does.
