### ISSUE TITLE
[Request] Support for message-attachments "image_url"

### ISSUE THREAD

**Issue by strangeminds** [CircleCI-Public/slack-orb#78]
We would like to add images to our CircleCI slack notifications using the orb.  Right now when we include a giphy URL to the message, it does not render the gif in Slack.

Request to add support for Slack message-attachment **image_url**

https://api.slack.com/docs/message-attachments

```
version: 2.1
orbs:
  slack: circleci/slack@3.3.0
jobs:
  fireworks:
    machine: true
    steps:
      - slack/notify:
          message: "https://giphy.com/gifs/fireworks-IjmMzurYulKEw"
          webhook: ${SLACK_WEBHOOK}
```
